# Generated by Django 5.2.8 on 2025-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='specialization title')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('medical_license_number', models.CharField(max_length=50, unique=True, verbose_name='medical license number')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('date_birth', models.DateTimeField(blank=True, null=True, verbose_name='date birth')),
                ('specializations', models.ManyToManyField(to='main.specialization', verbose_name='specializations')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['full_name'],
            },
        ),
    ]
