# Generated by Django 5.2.8 on 2025-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date birth'),
        ),
    ]
